version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - manager
      - mongodb
      - ollama
    networks:
      - batman

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - batman

  manager:
    image: code_manager:latest
    container_name: code_manager
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
      - ollama
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - batman

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /home/daktollo/SEP/KG/onlineCompiler/mongodb/data:/data/db
    ports:
      - "27018:27017"
    networks:
      - batman

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11433:11433"
    volumes:
      - /home/daktollo/SEP/KG/onlineCompiler/ollama/data:/root/.ollama
    networks:
      - batman
    depends_on:
      - mongodb
    environment:
      - OLLAMA_HOST=0.0.0.0:11433
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

networks:
  batman:
    driver: bridge
    name: batman

volumes:
  ollama_storage:
