version: '3.8'
services:
  webapp:
    image: webapp:latest
    container_name: webapp
    ports:
      - "5200:5200"
    depends_on:
      - manager
      - mongodb
      - ollama
    #volumes:
      #- /home/daktollo/Desktop/SEP/Bitirme/onlineCompiler/app/:/app
    #command: tail -f /dev/null
    networks:
      - batman

  manager:
    image: code_manager:latest
    container_name: code_manager
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
      - ollama
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - batman

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /home/daktollo/Desktop/SEP/Bitirme/onlineCompiler/mongodb/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - batman

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11433:11433"
    volumes:
      - /home/daktollo/Desktop/SEP/Bitirme/onlineCompiler/ollama/data:/root/.ollama
    networks:
      - batman
    depends_on:
      - mongodb
    environment:
      - OLLAMA_HOST=0.0.0.0:11433
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  batman:
    driver: bridge
    name: batman

volumes:
  ollama_storage:
